db.restaurante.find({})
db.restaurante.find({}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurante.find({}, { _id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurante.find({}, { _id: 0, restaurant_id: 1, name: 1, borough: 1, "address.zipcode": 1 })
db.restaurante.find({ "borough": "Bronx" })
db.restaurante.find({ "borough": "Bronx" }).limit(5)
db.restaurante.find({ "borough": "Bronx" }).skip(5).limit(5)
db.restaurante.find({ "grades.score": { $gt: 90 } })
db.restaurante.find({ "grades.score": { $gt: 80, $lt: 100 } })
db.restaurante.find({ "address.coord.0": { $lt: -95.754168 } })
db.restaurante.find({ "cuisine": { $ne: "American" }, "grades.score": { $gt: 70 }, "address.coord.0": { $lt: -65.754168 }})
db.restaurante.find({ "cuisine": { $ne: "American" }, "grades.score": { $gt: 70 }, "address.coord.0": { $lt: -65.754168 }})
db.restaurante.find({ "cuisine": { $ne: "American" }, "grades.grade": "A", "borough": { $ne: "Brooklyn" }}).sort({ "cuisine": -1 })
db.restaurante.find({ "name": { $regex: /^Wil/ },}, { "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1 })
db.restaurante.find({ "name": { $regex: /ces$/ } }, { "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1 })
db.restaurante.find({ "name": { $regex: /Reg/ } }, { "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1 })
db.restaurante.find({ "borough": "Bronx", "cuisine": { $in: ["American", "Chinese"] } })
db.restaurante.find({ "borough": { $in: ["Staten Island", "Queens", "Bronx", "Brooklyn"] } }, { "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1 })
db.restaurante.find({ "borough": { $nin: ["Staten Island", "Queens", "Bronx", "Brooklyn"] } }, { "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1 })
db.restaurante.find({ "grades.score": { $lt: 10 } }, { "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1 })
db.restaurante.find({$or: [{cuisine : {$nin : ["American ", "Chinese"]}}, {name : /^Wil/}]}, {restaurant_id : 1, name : 1, borough : 1, cuisine :1})
db.restaurante.find({ "grades": { $elemMatch: { "grade": "A", "score": 11, "date": ISODate("2014-08-11T00:00:00Z")}}}, {"restaurant_id": 1, "name": 1, "grades": 1})
db.restaurante.find({ "grades": { $elemMatch: { $and: [ { "grade": "A" }, { "score": 9 }, { "date": ISODate("2014-08-11T00:00:00Z") }]}}}, {"restaurant_id": 1,"name": 1,"grades.$": 1})
db.restaurante.find({ "address.coord.1": { $gt: 42, $lte: 52 }}, {"restaurant_id": 1, "name": 1, "address": 1})
db.restaurante.find().sort({ "name": 1 })
db.restaurante.find().sort({ "name": -1 })
db.restaurante.find().sort({ "cuisine": 1, "borough": -1 })
db.restaurante.find({ "address.street": { $exists: false }}, {"address": 1})
db.restaurante.find({ "address.coord": { $type: "double" }})
db.restaurants.find({'grades.score' : {$mod : [7, 0]}}, {restaurant_id : 1, name : 1, grades : 1})
db.restaurante.find({ "name": { $regex: /mon/i }}, { "name": 1, "borough": 1, "address.coord": 1,"cuisine": 1})
db.restaurante.find({ "name": { $regex: /^Mad/i } }, { "name": 1, "borough": 1,"address.coord": 1, "cuisine": 1})


